## Demo Playbook for Setting up First EC2 Instance
# 1) Creates custom security group
# 2) Spins up new EC2 Instances
# 3) Waits for ssh to become active on Instance
# 4) Saves Public IP address to hosts file
#
# Version 1.2      Kristan Edwards 
#
# Amazon Linux AMI ami-43874721
# Ubuntu Server LTS ami-33ab5251


- hosts: localhost

  tasks: 

  - name: Setting up Security Group
    ec2_group:
       name: WebServer_AWS_Security_Group
       description: Rules Allowing Traffic on port 22 and 80
       region: ap-southeast-2
       rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
       rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

  - name: Provision an EC2 Instance
    ec2:
        key_name: Kris10-AWSKey
        region: ap-southeast-2
        instance_type: t2.micro
        image: ami-33ab5251
        wait: true
        wait_timeout: 500
        count: 1
        instance_tags:
            Name: awsWebServer
            Owner: Kristan
        monitoring: no
        vpc_subnet_id: subnet-f58473ad
        assign_public_ip: yes
        group: WebServer_AWS_Security_Group
    register: ec2_out

  - name: Wait for SSH to come up
    wait_for: 
         host: "{{ item.public_dns_name }}"
         port: 22 
         delay: 60 
         timeout: 320 
         state: started
    with_items: '{{ec2_out.instances}}'

  - name: Save Public IP to hosts file
    lineinfile: 
         create: yes
         dest: ./inventory/hosts
         line: "{{ item.public_ip }}"
         state: present
    with_items: '{{ ec2_out.instances }}' 
